# Generated by Django 5.1.4 on 2025-01-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('Official', 'Official'), ('Normal', 'Normal')], max_length=100)),
            ],
        ),
    ]
