# Generated by Django 5.1.4 on 2025-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_email_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Official', 'Official'), ('Normal', 'Normal'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
